"use client";

import useEmblaCarousel from "embla-carousel-react";
import { ChevronLeft, ChevronRight } from "lucide-react";
import { useCallback, useEffect, useState } from "react";

import { Dialog, DialogPortal, DialogTrigger } from "@/shared/components/ui/dialog";

import { ImageViewer } from "./image-viewer";
import { ScreenshotThumbnail } from "./screenshot-thumbnail";

interface Screenshot {
  src: string;
  alt: string;
}

// Generated by flutter_guide_app's scripts/screenshot.sh; copy
// screenshots/en/*.png from that repo into public/screenshots/ after a
// release that changes any of these screens, and update this list to
// match.
const screenshots: Screenshot[] = [
  {
    src: "/screenshots/01_home.png",
    alt: "Home screen with the Elements and UIs categories, and a list of component categories like Text, Button, Form, and Picker",
  },
  {
    src: "/screenshots/02_catalog_elements.png",
    alt: "Elements catalog list",
  },
  {
    src: "/screenshots/03_catalog_uis.png",
    alt: "UIs catalog list",
  },
  {
    src: "/screenshots/04_elements_tab.png",
    alt: "An element's live preview",
  },
  {
    src: "/screenshots/05_component_detail.png",
    alt: "A component's detail screen, showing its live preview and a Favorite button",
  },
  {
    src: "/screenshots/06_component_code.png",
    alt: "A component's detail screen, showing its source code",
  },
  {
    src: "/screenshots/07_packages_tab.png",
    alt: "Packages catalog list",
  },
  {
    src: "/screenshots/08_settings.png",
    alt: "Settings screen",
  },
  {
    src: "/screenshots/09_code_theme_selector.png",
    alt: "Code theme selector, showing several syntax highlighting themes with a live code preview",
  },
];

export const ScreenshotsCarousel = () => {
  const [emblaRef, emblaApi] = useEmblaCarousel({ loop: false });

  const [canScrollPrev, setCanScrollPrev] = useState<boolean>(false);
  const [canScrollNext, setCanScrollNext] = useState<boolean>(false);
  const [selectedIndex, setSelectedIndex] = useState<number>(0);
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const scrollPrev = useCallback(() => emblaApi?.scrollPrev(), [emblaApi]);
  const scrollNext = useCallback(() => emblaApi?.scrollNext(), [emblaApi]);

  const onDotButtonClick = useCallback(
    (index: number) => {
      if (!emblaApi) return;
      emblaApi.scrollTo(index);
    },
    [emblaApi],
  );

  const onSelect = useCallback(() => {
    if (!emblaApi) return;

    setCanScrollPrev(emblaApi.canScrollPrev());
    setCanScrollNext(emblaApi.canScrollNext());
    setSelectedIndex(emblaApi.selectedScrollSnap());
  }, [emblaApi]);

  useEffect(() => {
    if (!emblaApi) return;

    onSelect();

    emblaApi.on("select", onSelect);
    emblaApi.on("reInit", onSelect);

    return () => {
      emblaApi.off("select", onSelect);
      emblaApi.off("reInit", onSelect);
    };
  }, [emblaApi, onSelect]);

  return (
    <div className="flex w-full flex-col items-center">
      <div className="w-full overflow-hidden" ref={emblaRef}>
        <div className="flex">
          {screenshots.map(({ src, alt }, index) => (
            <div
              key={index}
              className="min-w-0 flex-[0_0_100%] px-2 sm:flex-[0_0_50%] md:flex-[0_0_33.3333%] lg:flex-[0_0_25%]"
            >
              <Dialog
                open={openIndex === index}
                onOpenChange={(open) => setOpenIndex(open ? index : null)}
              >
                <DialogTrigger
                  className="relative flex h-full max-h-[70vh] w-full cursor-pointer items-center justify-center border-0 bg-transparent p-0"
                  aria-label={`View screenshot ${index + 1}`}
                >
                  <ScreenshotThumbnail src={src} alt={alt} priority={index === 0} />
                </DialogTrigger>

                <DialogPortal>
                  <ImageViewer src={src} alt={alt} />
                </DialogPortal>
              </Dialog>
            </div>
          ))}
        </div>
      </div>

      <div className="mt-8 flex items-center justify-center gap-4">
        <button
          onClick={scrollPrev}
          disabled={!canScrollPrev}
          className="flex rounded-full border border-zinc-700 bg-zinc-800 p-2 text-zinc-300 shadow-lg transition-colors duration-200 hover:bg-zinc-700 hover:text-white focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:outline-none disabled:pointer-events-none disabled:opacity-50"
          aria-label="Previous screenshot"
        >
          <ChevronLeft className="h-6 w-6" />
        </button>

        <div className="flex w-59 gap-1">
          {screenshots.map((_, index) => (
            <div key={index} className="flex h-2 w-4 items-center justify-center">
              <button
                onClick={() => onDotButtonClick(index)}
                className={`h-2 cursor-pointer rounded-full transition-all duration-200 ${
                  index === selectedIndex ? "w-4 bg-blue-500" : "w-2 bg-zinc-600 hover:bg-zinc-500"
                }`}
                aria-label={`Go to slide ${index + 1}`}
              />
            </div>
          ))}
        </div>

        <button
          onClick={scrollNext}
          disabled={!canScrollNext}
          className="flex cursor-pointer rounded-full border border-zinc-700 bg-zinc-800 p-2 text-zinc-300 shadow-lg transition-colors duration-200 hover:bg-zinc-700 hover:text-white focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:outline-none disabled:pointer-events-none disabled:opacity-50"
          aria-label="Next screenshot"
        >
          <ChevronRight className="h-6 w-6" />
        </button>
      </div>
    </div>
  );
};
